# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - bash: echo “Build”
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev105110-Adonis Test project-ServiceNow DevOps Service Connection'
        artifactsPayload: |
          {
            "artifacts": [
                {
                  "name": "adonis-devops.war",
                  "version": "1.$(Build.BuildId)",
                  "semanticVersion": "1.$(Build.BuildId).0",
                  "repositoryName": "Pipeline 1"
                }
            ]
          }


- stage: Test
  jobs:
  - job: Unit_Tests
    steps:
    - script: echo “Unit Tests”
    - task: CmdLine@2
      inputs:
        script: |
          NOW=$(date +"%Y-%m-%dT%T-0500")
          testPayload='{"name":"Test-summary-1.$(Build.BuildId).0","duration":0.0,"passedTests":10,"failedTests":1,"skippedTests":0,"blockedTests":0,"totalTests":11,"startTime":"'$NOW'","finishTime":"'$NOW'","artifacts":[{"name":"adonis-devops.war","version":"1.$(Build.BuildId)"}]}'
          echo $testPayload
          curl -X POST -H 'Content-Type: application/json' -u 'devops.integration.user:nE9njUJZ&!98'  -d $testPayload 'https://dev105110.service-now.com//api/sn_devops/v1/devops/tool/test?orchestrationToolId\=ada03cf897420110b33af5b3f153af52\&toolId=db976dc997020110b33af5b3f153af54'


  - job: 'Checkmarx_Scan'
    steps:
    - script: echo Checkmarx Scan
    - task: CmdLine@2
      inputs:
        script: |
          NOW=$(date +"%Y-%m-%dT%T-0500")
          curl -X POST -H 'Content-Type: application/json' -u 'devops.integration.user:nE9njUJZ&!98'  -d '{"scanID":"SCAN1","scannerName":"SonarQube","projectName":"aws-devops","lastScanned":"2022-02-04T22:57:15.175Z","initiatedBy":"adonis.peguero@rapdev.io","softwareQualityDetail":[{"category":"vulnerabilities","value":"20","categoryDetail":[{"subcategory":"critical","value":"2"},{"subcategory":"high","value":"4"},{"subcategory":"medium","value":"4"},{"subcategory":"minor","value":"10"}]},{"category":"license_risks","result":"PASS","actual":"2","expected":"<5"}],"artifacts":[{"name":"rapdev-web.war","version":"1.0.5"}]}' 'https://dev105110.service-now.com//api/sn_devops/v1/devops/tool/softwarequality?orchestrationToolId=ada03cf897420110b33af5b3f153af52&toolId=3e27ef1597064110b33af5b3f153af14'

- stage: Deploy
  jobs:
  - job: UAT_Deploy
    steps:
    - bash: echo “UAT Deploy”
    - task: ServiceNow-DevOps-Agent-Package-Registration@1
      inputs:
        connectedServiceName: 'dev105110-Adonis Test project-ServiceNow DevOps Service Connection'
        packageName: 'Can be anything'
        artifactsPayload: |
          {
              "artifacts": [
              {
                  "name": "adonis-devops.war",
                  "repositoryName": "Pipeline 1",
                  "version": "1.$(build.buildId)",
                  "currentBuildInfo": "true"
              }]
          }



  - job:  Production_Deploy
    dependsOn: 'UAT_Deploy'
    steps:
    - bash: echo “Production Deploy”
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'dev105110-Adonis Test project-ServiceNow DevOps Service Connection'
        changeRequestDetails: |
          {
              "setCloseCode" : true,
              "attributes": {
                "requested_by": {
                  "name": "test user"
                },
                "start_date": "2021-01-05 08:00:00",
                "end_date": "2021-01-08 08:00:00"
              }
            }