# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - bash: echo “Build”
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev105110-Adonis Test project-ServiceNow DevOps Service Connection'
        artifactsPayload: |
          {
             "artifacts": [
                {
                   "name": "_Pipeline 1",
                   "version": "1.$(Build.BuildId)",
                   "semanticVersion": "1.$(Build.BuildId).0",
                   "repositoryName": "Pipeline 2"
                }
             ]
          }

- stage: Test
  jobs:
  - job: Unit_Tests
    steps:
    - bash: echo “Unit Tests”

