# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - bash: echo “Build”
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev105110-Adonis Test project-ServiceNow DevOps Service Connection'
        artifactsPayload: |
          {
            "artifacts": [
                {
                  "name": "_Pipeline 1",
                  "version": "1.$(Build.BuildId)",
                  "semanticVersion": "1.$(Build.BuildId).0",
                  "repositoryName": "Pipeline 1"
                }
            ]
          }

- stage: Test
  jobs:
  - job: Unit_Tests
    steps:
    - script: echo “Unit Tests”
    - task: CmdLine@2
      inputs:
        script: |
          NOW=$(date +"%Y-%m-%dT%T-0500")
          testPayload='{"name":"Test-summary-1.$(Build.BuildId).0","duration":0.0,"passedTests":10,"failedTests":1,"skippedTests":0,"blockedTests":0,"totalTests":11,"startTime":"'$NOW'","finishTime":"'$NOW'","artifacts":[{"name":"CorpSite-artifact","version":"1.$(Build.BuildId)"}]}'
          echo $testPayload
          curl -X POST -H 'Content-Type: application/json' -u 'devops.integration.user:ejtighymydjevxyqzvfcrp7bnrr5raiqx4onnfi66stks2uwg53q'  -d $testPayload 'https://%3CDevOps%20integration%20user%20ID%3E:%3Cintegration%20user%20password%3E@dev105110.service-now.com/api/sn_devops/v1/devops/tool/%7Bcode%20%7C%20plan%20%7C%20artifact%20%7C%20orchestration%20%7C%20test%20%7C%20softwarequality%20%7D?toolId=ada03cf897420110b33af5b3f153af52'

  - job:  Checkmarx_Scan
    steps:
    - bash: echo “Checkmarx Scan”

- stage: Deploy
  jobs:
  - job: UAT_Deploy
    steps:
    - bash: echo “UAT Deploy”
    - task: ServiceNow-DevOps-Agent-Package-Registration@1
      inputs:
        connectedServiceName: 'dev105110-Adonis Test project-ServiceNow DevOps Service Connection'
        packageName: 'Can be anything'
        artifactsPayload: |
          {
              "artifacts": [
              {
                  "name": "_Pipeline 1",
                  "repositoryName": "Pipeline 1",
                  "version": "1.$(build.buildId)",
                  "currentBuildInfo": "true"
              }]
          }
  - job:  Production_Deploy
    steps:
    - bash: echo “Production Deploy”

