# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Software_Quality
  jobs:
  - job: Checkmarx_Scan
    steps:
    - bash: echo “Checkmarx scan”
    - task: CmdLine@2
      inputs:
        script: |
          NOW=$(date +"%Y-%m-%dT%T-0500")
          curl -X POST -H 'Content-Type: application/json' -u 'devops.integration.user:nE9njUJZ&!98'  -d '{"scanID": "SCAN001","scannerName": "SonarQube", "projectName": "app-devops", "initiatedBy": "adonis.peguero@rapdev.io","lastScanned": "2021-11-16T11:20:00","scanURL": "https://abc.com","shortDescription": "test scan","softwareQualityDetail": [{"category": "vulnerabilities", "value": "20", "categoryDetail": [ {"subcategory": "critical","value": "2"}]}],"artifacts": [{"name": "CorpSite-artifact", "version": "1.0.0"}]}' 'https://dev105110.service-now.com//api/sn_devops/v1/devops/tool/test?orchestrationToolId=ada03cf897420110b33af5b3f153af52&toolId=3e27ef1597064110b33af5b3f153af14'

    
- stage: Deploy
  jobs:
  - job: Production_Deploy
    steps:
    - bash: echo “Production Deploy”
